### ISSUE TITLE
Running schedule jobs run on specific time

### ISSUE THREAD

**Issue by yongkylie** [jamplify/mongo-scheduler#12]
Is it possible to run schedule job on specific time (e.g 12 AM everyday, or in every 5 minutes since the server starts) to update documents or to do database backup on daily basis? Seems like the description is lacking of examples regarding scheduling time.

Any help would be appreciated :D

**Comment by sivapushnam** [comment]
If you wan to schedule a events for every 5 mins, just try with below sample.
var event = {name: 'breakfast' collection: 'meals', after: new Date(), data: 'Fry', cron: '*/5 * * * *'}
scheduler.schedule(event)
But there is not End time to stop the schedule events emitting.
